### ISSUE TITLE
character.data.frame returns malformed column names

### ISSUE THREAD

**Issue by dklein-pik** [pik-piam/quitte#5] opened 2020-04-07 15:58 UTC
It seem with the latest version of the tibble package (tibble_3.0.0) the quitte function `character.data.frame()` returns malformed column names. With an older tibble version (tibble_2.1.1) it worked on my local machine. The issue occured after updating tibble on my local machine.

The result of:
`character.data.frame(as.quitte(read.report("REMIND_generic_SSP2-Base.mif",as.list = FALSE)))`

Result with tibble_2.1.1:

```
#A tibble: 356,174 x 7
   model  scenario  region variable    unit               period value
   <chr>  <chr>     <chr>  <chr>       <chr>               <int> <dbl>
 1 REMIND SSP2-Base CAZ    Consumption billion US$2005/yr   2005 1122.
 2 REMIND SSP2-Base CHA    Consumption billion US$2005/yr   2005 1604.
 3 REMIND SSP2-Base EUR    Consumption billion US$2005/yr   2005 8753.
 4 REMIND SSP2-Base IND    Consumption billion US$2005/yr   2005  517.
 5 REMIND SSP2-Base JPN    Consumption billion US$2005/yr   2005 3032.
 6 REMIND SSP2-Base LAM    Consumption billion US$2005/yr   2005 1867.
 7 REMIND SSP2-Base MEA    Consumption billion US$2005/yr   2005  996.
 8 REMIND SSP2-Base NEU    Consumption billion US$2005/yr   2005  943.
 9 REMIND SSP2-Base OAS    Consumption billion US$2005/yr   2005 1300.
10 REMIND SSP2-Base REF    Consumption billion US$2005/yr   2005  570.
 #... with 356,164 more rows
```

Result with tibble_3.0.0:

```
# A tibble: 356,174 x 7
   model[,"model"] [,"scenario"] [,"region"] [,"variable"] [,"unit"] scenario[,"mode~ [,"scenario"] [,"region"] [,"variable"] [,"unit"] region[,"model"]
   <chr>           <chr>         <chr>       <chr>         <chr>     <chr>            <chr>         <chr>       <chr>         <chr>     <chr>           
 1 REMIND          SSP2-Base     CAZ         Consumption   billion ~ REMIND           SSP2-Base     CAZ         Consumption   billion ~ REMIND          
 2 REMIND          SSP2-Base     CHA         Consumption   billion ~ REMIND           SSP2-Base     CHA         Consumption   billion ~ REMIND          
 3 REMIND          SSP2-Base     EUR         Consumption   billion ~ REMIND           SSP2-Base     EUR         Consumption   billion ~ REMIND          
 4 REMIND          SSP2-Base     IND         Consumption   billion ~ REMIND           SSP2-Base     IND         Consumption   billion ~ REMIND          
 5 REMIND          SSP2-Base     JPN         Consumption   billion ~ REMIND           SSP2-Base     JPN         Consumption   billion ~ REMIND          
 6 REMIND          SSP2-Base     LAM         Consumption   billion ~ REMIND           SSP2-Base     LAM         Consumption   billion ~ REMIND          
 7 REMIND          SSP2-Base     MEA         Consumption   billion ~ REMIND           SSP2-Base     MEA         Consumption   billion ~ REMIND          
 8 REMIND          SSP2-Base     NEU         Consumption   billion ~ REMIND           SSP2-Base     NEU         Consumption   billion ~ REMIND          
 9 REMIND          SSP2-Base     OAS         Consumption   billion ~ REMIND           SSP2-Base     OAS         Consumption   billion ~ REMIND          
10 REMIND          SSP2-Base     REF         Consumption   billion ~ REMIND           SSP2-Base     REF         Consumption   billion ~ REMIND          
# ... with 356,164 more rows, and 16 more variables: [,"scenario"] <chr>, [,"region"] <chr>, [,"variable"] <chr>, [,"unit"] <chr>, variable[,"model"] <chr>,
#   [,"scenario"] <chr>, [,"region"] <chr>, [,"variable"] <chr>, [,"unit"] <chr>, unit[,"model"] <chr>, [,"scenario"] <chr>, [,"region"] <chr>, [,"variable"] <chr>,
#   [,"unit"] <chr>, period <int>, value <dbl>
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2020-04-08 09:03
This issue was around for some time, but the new tibble version seems to have escalated it.  The problem is extra attributes on the columns nobody asked for. Fixed in f1120efaca243c6f1bd53b111a621fac9eab7def.

**Closed by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** 2020-04-08 09:03 UTC
Labels: bug
