### ISSUE TITLE
build fail - depreciation warning from forcats

### ISSUE THREAD

**Issue by bs538** [pik-piam/quitte#45] opened 2023-01-31 15:57 UTC
building piamInterfaces fails with the following 
```
══ Warnings ════════════════════════════════════════════════════════════════════
1. test summationFile without errors using AR6 ('test-checkSummations.R:22') - `fct_explicit_na()` was deprecated in forcats 1.0.0.
ℹ Please use `fct_na_value_to_level()` instead.
ℹ The deprecated feature was likely used in the quitte package.
  Please report the issue at <https://github.com/pik-piam/quitte/issues>.

══ DONE ════════════════════════════════════════════════════════════════════════
Before submission you need to take care of the following warnings:

test "test summationFile without errors using AR6": `fct_explicit_na()` was deprecated in forcats 1.0.0.
ℹ Please use `fct_na_value_to_level()` instead.
ℹ The deprecated feature was likely used in the quitte package.
  Please report the issue at <https://github.com/pik-piam/quitte/issues>.

You can find solutions to common problems at https://github.com/pik-piam/discussions/discussions/18
Error in lucode2::verifyTests(...) : The package tests produced warnings.
 Error in check(cran = cran, config = cfg) : lucode2::check failed
```

**Comment by orichters** [comment] 2023-02-01 13:10
I think we still should fix that problem in quitte, caused by the deprecation of `fct_explicit_na` in forcats: https://github.com/tidyverse/forcats/releases/tag/v1.0.0

@tscheypidi: It seems we have to replace `fct_explicit_na` by `fct_na_value_to_level`, but would be great if you could check.

**Comment by tscheypidi** [comment] 2023-02-01 13:17
I agree that this should be fixed and forward it to Michaja as the author of the corresponding [lines](https://github.com/pik-piam/quitte/blame/b23d6504f2757cf8f76eeb958d58ae9407b5db86/R/as.quitte.R)

**Closed** 2023-02-02 09:01 UTC
